<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="robotv1" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:include filename="$(find robotv1_description)/urdf/lower_body.xacro"/>
  <xacro:include filename="$(find robotv1_description)/urdf/upper_body.xacro"/>
  <link name="world">
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="pelvis"/>
    <origin xyz="0 0 1"/>
  </joint>


  <joint name="pelvis_torso_joint" type="fixed">
    <parent link="pelvis"/>
    <child link="torso"/>
    <origin xyz="0 0 ${lenz_pelvis/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${2*pi}" effort="${elbowEff}" velocity="${elbowVel}"/>
  </joint>
    
   
</robot>
