robotv1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  leftarm_shoulder_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftarm_shoulder_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  leftarm_shoulder_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftarm_shoulder_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  leftarm_elbow_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftarm_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  leftarm_wrist_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftarm_wrist_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  leftarm_wrist_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftarm_wrist_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
   
