robotv1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  leftleg_hip_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_hip_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  leftleg_hip_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_hip_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftleg_hip_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_hip_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftleg_knee_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_knee_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftleg_ang_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_ang_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftleg_ang_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: leftleg_ang_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
   
  rightleg_hip_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_hip_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightleg_hip_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_hip_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightleg_hip_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_hip_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightleg_knee_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_knee_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightleg_ang_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_ang_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightleg_ang_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rightleg_ang_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
 
